import { prefix } from 'src/modules/shows/reducers'

export const GET_SHOWS_REQUEST = `${prefix}/GET_SHOWS_REQUEST`
export const GET_SHOWS_SUCCESS = `${prefix}/GET_SHOWS_SUCCESS`
export const GET_SHOWS_FAILURE = `${prefix}/GET_SHOWS_FAILURE`

export const GET_SHOW_CAST_REQUEST = `${prefix}/GET_SHOW_CAST_REQUEST`
export const GET_SHOW_CAST_SUCCESS = `${prefix}/GET_SHOW_CAST_SUCCESS`
export const GET_SHOW_CAST_FAILURE = `${prefix}/GET_SHOW_CAST_FAILURE`

export const GET_SHOW_DETAILS_REQUEST = `${prefix}/GET_SHOW_DETAILS_REQUEST`
export const GET_SHOW_DETAILS_SUCCESS = `${prefix}/GET_SHOW_DETAILS_SUCCESS`
export const GET_SHOW_DETAILS_FAILURE = `${prefix}/GET_SHOW_DETAILS_FAILURE`

export const GET_SHOW_SEASONS_REQUEST = `${prefix}/GET_SHOW_SEASONS_REQUEST`
export const GET_SHOW_SEASONS_SUCCESS = `${prefix}/GET_SHOW_SEASONS_SUCCESS`
export const GET_SHOW_SEASONS_FAILURE = `${prefix}/GET_SHOW_SEASONS_FAILURE`

export const GET_SHOW_EPISODES_REQUEST = `${prefix}/GET_SHOW_EPISODES_REQUEST`
export const GET_SHOW_EPISODES_SUCCESS = `${prefix}/GET_SHOW_EPISODES_SUCCESS`
export const GET_SHOW_EPISODES_FAILURE = `${prefix}/GET_SHOW_EPISODES_FAILURE`

